name: StreetCoffee
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Rx
  rxdart: ^0.22.2

  # Save Data
  shared_preferences: ^0.4.3

  # Card code
  slimy_card: ^1.0.4
  
  # Firebase
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.1.6
  firebase_messaging: ^6.0.9

  # Icon
  cupertino_icons: ^0.1.3
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google.jpg
    - assets/images/facebook.jpg
    - assets/images/coffee.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #